# CodeRabbit configuration
language: en-US
early_access: false
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base: auto
    ignored_files:
      - "^.github/"
chat:
  auto_reply: true